---
title: "SarePoint Package"
subtitle: "Ryan Hill, 09/03/2026"
abstract: "SharePoint package in R."
header-includes:
   - \usepackage{amsmath}
output: 
  pdf_document: default
  df_print: paged
geometry:
  - tmargin=1.5cm
  - bmargin=1.5cm
  - lmargin=1.5cm
  - rmargin=1.5cm 
---
\fontsize{10}{10}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, out.width="65%", size="small")
```


### 0.0.0 - Packages Used in Report

```{r warning=FALSE, message=FALSE, results='hide'}
if(!require(pacman)){install.packages("pacman")}
pacman::p_load(knitr, tidyverse, dplyr, sharepointr)
```


### 1.0.0 - The SharePoint R package

```{r installing-package}

# line to install the package for first time
# remotes::install_github("department-for-transport-public/sharepointr")

```

See the following link for guideance: https://github.com/department-for-transport-public/sharepointr

```{r using-SharePointr}

## test the following
# reading files
# uploading files
# saving outputs directly to SharePoint (and not on local repository)

# SharePoint URL = https://departmentfortransportuk.sharepoint.com/sites/MSRSRetrospectiveEvaluation-ExternalChannelRT-FAB-LSCA/Shared%20Documents/Forms/AllItems.aspx?FolderCTID=0x01200060A658E9F5AB5049B3798193E807C78E&id=%2Fsites%2FMSRSRetrospectiveEvaluation%2DExternalChannelRT%2DFAB%2DLSCA%2FShared%20Documents%2FGeneral%2FIpsos%5FAtkins%20working%20docs

yoursite <- "MSRSRetrospectiveEvaluation-ExternalChannelRT-FAB-LSCA"
Shared_Documents <- "Shared_Documents"
yourfolder <- "Forms/AllItems.aspx?FolderCTID=0x01200060A658E9F5AB5049B3798193E807C78E&id=%2Fsites%2FMSRSRetrospectiveEvaluation%2DExternalChannelRT%2DFAB%2DLSCA%2FShared%20Documents%2FGeneral%2FIpsos%5FAtkins%20working%20docs" 

list_sharepoint_objects(site = yoursite, drive = Shared_Documents, path = yourfolder)
# the following needs admin approval, I think from AR side


```
